//Homepage application
window.bmHomepage = (function() {
    'use strict';

    /**
     * Public variables
     */
    var bmHomepage = {};
    var params = {
        errors : []
    };
 
 
    /**
     * Start the application
     * @returns {undefined}
     */
    bmHomepage.load = function() {
        //Add a last class to the subtiles for IE8 support
        $('.lt-ie9 #subtiles .subtile:last').addClass('last');
        //Add tracking links
        trackingLinks();
        //Check if the preview string is set, load the preview mode options
        if (window.urlParams.preview === 'true') {
            preview();
        }
    };


    /**
     * Appends autogenerated tracking links to homepage panels for marketing purposes.
     * The tracking link is a query parameter that has the panels location, language and ID
     * This hooks into window.Modernizr which is loaded by scripts.pre in the head
     * EXAMPLE: ?icamp=INTC_HP_Panel_Row1Col1_30dataBoostUp
     * @returns {undefined}
     */
    var trackingLinks = function(){
       //Set default parameters
        var lang = 'HP';
        if (window.Modernizr.user === 'customer' && window.urlParams.lang !== 'esp') {
            lang = 'CHP';
        } else  if (window.location.host === 'espanol.boostmobile.com' || window.urlParams.lang === 'esp') {
            lang = 'SHP';
        } else  if ((window.location.host === 'espanol.boostmobile.com' || window.urlParams.lang === 'esp') && window.Modernizr.user === 'customer') {
            lang = 'SCHP';
        }
        
        //Loop through the rows
        $.each($('.row'), function(index) {
            var row = index + 1;
            //Loop through the columns within that row
            $.each($(this).find('.home-panel'), function(index2) {
                var column = index2 + 1;
                var id = $(this).attr('id');
                //Now loop through the links within that column
                $.each($(this).find('a'), function() {
                    //Update URL with the correct tracking parameter
                    var slug = updateQueryString('icamp', 'INTC_' + lang + '_Panel_Row' + row + 'Col' + column + '_' + id, this.href);
                    $(this).attr('href',slug);
                });
            });
        });
        
        //Update subtile tracking links
        $.each($('.subtile'), function(index){
            var pos = index + 1;
            var id = $(this).attr('id');
           
            $.each($(this).find('a'), function(){
                //Update URL with the correct tracking parameter
                //?icamp=INTC_SHP_3_Tile_MobileHotspot
                var slug = updateQueryString('icamp', 'INTC_' + lang + '_Tile' + pos + '_' + id, this.href);
                $(this).attr('href', slug);
            });
        });
    };//end addTrackingLinks
    
    
    /**
     * Display a previewbox in the top right of the screen that allows a business owner to easily toggle between the various homepage states
     * @type type
     */
    var preview = function() {
        //Default settings
        var settings = {
            lang: {category: 'Language', slug: 'lang'},
            user: {category: 'User', slug: 'user'}
        };

        if (window.urlParams.lang === 'esp') {
            settings.lang.value = 'eng';
            settings.lang.label = 'Spanish';
        } else {
            settings.lang.value = 'esp';
            settings.lang.label = 'English';
        }

        if (window.urlParams.user === 'customer') {
            settings.user.value = 'visitor';
            settings.user.label = 'Customer';
        } else {
            settings.user.value = 'customer';
            settings.user.label = 'Visitor';
        }

        //Create preview box in the DOM
        var previewBox = $('<div/>', {
            id: 'previewBox',
            style: 'width:185px;position:fixed;right:5px;top:5px;color:#000;background-color:#fff;padding:10px;z-index:200'
        });

        //Create content for preview box
        var previewContent = '<div class="full"><strong style="font-size:16px;">Preview Mode</strong><br/><span style="font-size:9px;">Currently Viewing</span><br/><br/>';
        //Loop through settings obj to get the toggleable options and create HTML for them
        $.each(settings, function() {
            previewContent += this.category + ': <a href="#" id="' + this.slug + '">' + this.label + '</a><br/>';
        });
        
        //Add Mobile Preview
        previewContent += '</div><hr/><div class="mobile"><a href="#" id="prevMobile">Show mobile banners</a></div>';
        previewContent += '<hr/><span>Spanish content will not be translated but will show the correct content and order.</span>';

        //Load content into preview box
        previewBox.html(previewContent);
        //Load into dom
        $('body').prepend(previewBox);

        //Load assets needed for mobile preview
        var prevMobile = '';
        //Load Facebox JS and CSS
        $.getScript("/_themes/libs/js/facebox.js");
        $("<link/>", {rel: "stylesheet", type: "text/css", href: "/_themes/libs/css/facebox.css"}).appendTo("head");
        //Load content from XML file
        $.ajax({
            url: "/_xml_conf/www/home.xml",
            dataType: 'xml'
        }).done(function(content) {
            //Get mobile XML node
            var response = $(content).find('mobile_images');
            //Loop through content in mobile image XML node and create HTML for output
            $(response).find('image').each(function() {
                var url = $(this).find('page_url').text();
                var src = $(this).find('image_src').text().replace('http:', '').replace('//www.boostmobile.com', '');
                prevMobile += '<p><a href="' + url + '"><img src="' + src + '"/></a><br/><span style="color:#fff;">' + url + '</span></p>';
            });
        });

        //Check for clicks in the preview box and redirect to URL with updated query params
        $("body").on("click", "#previewBox .full a", function() {
            window.location = updateQueryString(this.id, settings[this.id].value);
            return false;
        });
        //When the mobile banner button is clicked
        $("body").on("click", "#previewBox .mobile a", function() {
            $.facebox(prevMobile);
            return false;
        });
    };//end preview
    
    
    /**
     * Add/Update/Remove query string parameters from a supplied link
     * @param {String} key - Query string key
     * @param {String} value - Query string value
     * @param {String} url - (Optional) Specify the URL to update. If left blank will use current page
     * @returns {String} - The URL of with the added/updated/removed query param
     */
    var updateQueryString = function(key, value, url) {
        if (!url)
            url = window.location.href;
        var re = new RegExp("([?|&])" + key + "=.*?(&|#|$)(.*)", "gi");

        if (re.test(url)) {
            if (typeof value !== 'undefined' && value !== null)
                return url.replace(re, '$1' + key + "=" + value + '$2$3');
            else {
                return url.replace(re, '$1$3').replace(/(&|\?)$/, '');
            }
        }
        else {
            if (typeof value !== 'undefined' && value !== null) {
                var separator = url.indexOf('?') !== -1 ? '&' : '?',
                        hash = url.split('#');
                url = hash[0] + separator + key + '=' + value;
                if (hash[1])
                    url += '#' + hash[1];
                return url;
            }
            else
                return url;
        }
    };//end updateQueryString
    
    
    //Launch the application 
    try {
      bmHomepage.load();
    //Catch errors within this app to interfering with JS on the host page
    } catch (err) {
        params.errors.push(err);
    }

    //Make private properties available to the API with prefix
    bmHomepage._params = params;
    //Make API public
    return bmHomepage;
})();